version: '3'
services:
  app:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api_gateway:/api_gateway
    ports:
      - "3000:3000"
  booking:
    build: ./reservations
    command: rails s -b 0.0.0.0
    volumes:
      - ./reservations:/usr/src
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: