version: '3'
services:
  app:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api_gateway:/usr/src
    ports:
      - "3000:3000"
  reservations:
    build: ./reservations
    command: rails s -b 0.0.0.0
    volumes:
      - ./reservations:/usr/src
    ports:
      - "4000:4000"
    depends_on:
      - db
      - sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0
  sidekiq:
    build: ./reservations
    command: sidekiq
    volumes:
      - ./reservations:/usr/src
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
volumes:
  postgres:
  redis: